# 실습 WEEK4: 자료구조와 배열

:::{admonition} 안내 
:class: info  

- 실습 문제는 사전, 도전, 완전 실습 문제로 구성되어 있습니다.
- 사전 실습 문제는 수업 전에 미리 풀어보시면 도움이 됩니다.
- **<font color='blue'>도전 실습 문제는 etl>우리강좌>코딩수업>에 접속한 후, 해당 주차 문제의 소스코드를 제출하여 테스트를 통과해야 과제 점수를 받을 수 있습니다.</font>**
- **<font color='red'>제출기한은 실습수업시간부터 다음 실습수업 전날 자정까지</font>**입니다.
- 완전 실습 문제는 보너스 실습 문제로 생각하시면 됩니다.  도전 실습 문제를 다 풀어본 학생들이 추가적으로 풀어보시면 도움이 됩니다.
- 사전 실습 문제와 완전 실습 문제는 수업 시간에 별도 풀이를 하지 않습니다.
- 질문은 사전, 도전, 완전 그리고 수업과 관련된 모든 것에  대하여 교수자 or 조교 or 튜터에게 하시면 됩니다.
- **<font color='red'>가독성을 위해 입출력 데이터에서 콜론(:) 다음에는 항상 한칸 공백이 있습니다.</font>**

:::

### 데이터 입력과 출력 예
😄문자열을 입력받아 출력하시오.

---

<font color='blue'>`test case-1`</font> 

Input Sample
```
즐거워
```
Output Sample
```
문자열: 
출력결과: 즐거워
```


<font color='blue'>`test case-2`</font>

Input Sample
```
Say! I can do it!
```
Output Sample
```
문자열: 
출력결과: Say! I can do it! 
```

In [ ]:
input_data = input('문자열: ')
print(f'출력결과: {input_data}')

문자열: Say! I can do it!
출력결과: Say! I can do it!

## [사전 실습 문제]

### Problem: 상품재고관리프로그램
😄 변수 product에 상품 목록이 리스트로 저장되어 있습니다. 상품을  추가, 삭제, 검색, 정렬하는 상품재고관리 프로그램을 작성하시오.

작업번호는 종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5)이며 숫자로 입력합니다. 
추가, 삽입, 삭제, 검색, 정렬하고자 하는 상품명을 문자열로 입력합니다.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
1
사과
2
배
4
3
장난감
4
베개
4
피아노
5
1
5
2
0
```
Output Sample
 
```
상품재고관리 프로그램

현재 상품 리스트
['커피', '우유', '바나나', '감귤', '화장지', '장갑', '이불', '베개', '장난감', '음료수', '빵']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
추가상품명: 
사과 추가 완료

현재 상품 리스트
['커피', '우유', '바나나', '감귤', '화장지', '장갑', '이불', '베개', '장난감', '음료수', '빵', '사과']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
삽입상품명: 
삽입위치: 
배 삽입 완료

현재 상품 리스트
['커피', '우유', '바나나', '배', '감귤', '화장지', '장갑', '이불', '베개', '장난감', '음료수', '빵', '사과']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
삭제상품명: 
장난감 삭제 완료

현재 상품 리스트
['커피', '우유', '바나나', '배', '감귤', '화장지', '장갑', '이불', '베개', '음료수', '빵', '사과']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
검색상품명: 
베개 검색 됨

현재 상품 리스트
['커피', '우유', '바나나', '배', '감귤', '화장지', '장갑', '이불', '베개', '음료수', '빵', '사과']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
검색상품명: 
피아노 검색 안됨

현재 상품 리스트
['커피', '우유', '바나나', '배', '감귤', '화장지', '장갑', '이불', '베개', '음료수', '빵', '사과']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
오름차순(1) 내림차순(2): 

현재 상품 리스트
['감귤', '바나나', '베개', '빵', '우유', '음료수', '이불', '장갑', '장난감', '커피', '화장지']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
오름차순(1) 내림차순(2): 

현재 상품 리스트
['화장지', '커피', '장난감', '장갑', '이불', '음료수', '우유', '빵', '베개', '바나나', '감귤']
==========================================================================================

종료(0) 추가(1) 삽입(2) 삭제(3) 검색(4) 정렬(5): 
프로그램을 종료합니다.
```

In [ ]:
print('상품재고관리 프로그램')

product = '커피, 우유, 바나나, 감귤, 화장지, 장갑, 이불, 베개, 장난감, 음료수, 빵'.split(', ')

while True:
    print()    
    print('현재 상품 리스트')
    print(product)
    print('='*90)
    print()

    #TODO

### Problem: 컴또복권번호 set으로 만들기

😄 0~9까지의 숫자 가운데 중복되지 않은 4개의 정수를 랜덤으로 생성해 set으로 만들어 출력하는 프로그램을 작성하시오. 랜덤이므로 Output Sample의 숫자는 아래와 다를 수 있습니다.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
컴또복권번호: {8, 2, 4, 6}
```


<font color='blue'>`test case-2`</font>

Output Sample
```
컴또복권번호: {8, 9, 2, 5}
```

### Problem: 컴또복권번호 리스트로 만들기
😄 0~9까지의 숫자 가운데 중복되지 않은 4개의 정수를 랜덤으로 생성해 리스트로 만들어 출력하는 프로그램을 작성하시오. 랜덤이므로 Output Sample의 숫자는 아래와 다를 수 있습니다.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
컴또복권번호: [7, 4, 3, 6]
```


<font color='blue'>`test case-2`</font>

Output Sample
```
컴또복권번호: [9, 5, 0, 3]
```

### Problem: 딕셔너리 활용 칼로리 계산기
😄 체중(자연수, kg), 운동시간(자연수, 분), 운동종목을 입력받아 칼로리를 계산하는 프로그램을 작성하시오. 단, 아래에 있는 딕셔너리(ex_dict)를 활용하시오. ex_dict 내의 운동종목이 늘어나도 아래코드는 전혀 건들지 않도록 코딩해주세요. 즉, 유지보수가 쉽고, 확장성이 있어야 한다는 의미입니다.
```
METs(대사당량) 기준
걷기 : 4METs     조깅 : 7METs   
계단 : 5METs     수영 : 9METs

칼로리 =((METs * 3.5 * 체중(kg)) /200)*운동시간(분)

ex_dict={'걷기':4, '조깅':7, '계단오르기':5, '수영':9}
```
<font color='blue'>`test case-1`</font> 
---
Input Sample
```
60
10
걷기
```
Output Sample
```
체중(kg): 
운동시간(m): 
운동종목 ['걷기', '조깅', '계단오르기', '수영']: 
걷기 10분은 42.0kcal 소모
```

In [ ]:
ex_dict={'걷기':4, '조깅':7, '계단오르기':5, '수영':9}

### Problem: 동이름만 출력하기
😄 구 이름과 동 이름이 한칸씩 공백을 두고 입력됩니다. 그 중 동 이름만 출력하는 프로그램을 작성하시오. 

<font color='blue'>`test case-1`</font> 
---
Input Sample
```
강동구 노원구 용산구 상암동 서울시 논현동 가리봉동 평창동 중구 중동
```
Output Sample
```
Input: 
동이름: 상암동 논현동 가리봉동 평창동 중동
```
<font color='blue'>`test case-2`</font> 
---
Input Sample
```
우이동 공릉동 부산시 사하구 전라남도 명동 광주시 파이동 썬동 머신러닝
```
Output Sample
```
Input: 
동이름: 우이동 공릉동 명동 파이동 썬동
```

### Problem: 인기투표 정리하기
😄 변수 vote에는 BTS멤버의 인기투표 이름이 들어있다. 멤버가 각 몇 표를 받았는지 딕셔너리 타입으로 저장하여 출력하시오. 

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
{'슈가': 18, '진': 15, '정국': 14, 'RM': 20, '지민': 19, '제이홉': 14}
```

In [ ]:
vote='''슈가 진 정국 진 슈가 진 RM 지민 슈가 지민 진 제이홉 진 슈가 슈가 RM 지민 정국 슈가 지민 지민
진 RM 지민 진 지민 슈가 정국 제이홉 제이홉 슈가 제이홉 RM RM 슈가 제이홉 슈가 진 진 제이홉 정국
슈가 RM 지민 RM 지민 정국 RM 슈가 슈가 정국 슈가 슈가 지민 진 RM RM 진 RM 정국 제이홉 RM RM 지민
지민 RM RM 지민 제이홉 정국 정국 지민 진 제이홉 정국 진 슈가 정국 RM 지민 제이홉 RM 제이홉 슈가 슈가
지민 RM 지민 진 RM 정국 지민 제이홉 지민 정국 제이홉 RM 진 제이홉 정국'''

### Problem: 1차원 배열 생성하기
😄 출력결과와 같이 1차원 배열(array)를 생성해보세요.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
1-D array: [10 8 5 7 19]
```

### Problem: 2차원 배열 생성하기
😄 출력결과와 같이 2차원 배열(array)를 생성해보세요.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
2-D array: 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
```

### Problem: 3차원 배열 생성하기
😄 출력결과와 같이 3차원 배열(array)를 생성해보세요.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
3-D array: 
[[[100 90 80]
 [ 70 60 50]]

 [[ 15 25 35]
 [ 45 55 65]]

 [[ 11 22 33]
 [ 44 55 66]]]
```

### Problem: 실수형 랜덤 배열 생성하기1
😄 0이상 1미만의 임의의 실수값으로 채워진 3(면) x 3(행) x 2(열) 배열을 생성하여 배열의 모양과 함께 출력하시오.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
배열의 모양: (3, 3, 2)
[[[0.37376048 0.15396633]
  [0.96137267 0.55752608]
  [0.75176515 0.07312223]]

 [[0.42532833 0.57415501]
  [0.07496968 0.88594487]
  [0.28332782 0.2971798 ]]

 [[0.44362661 0.76007254]
  [0.27045252 0.35849775]
  [0.22908071 0.42359505]]]
```

### Problem: 실수형 랜덤 배열 생성하기2
😄 4.5이상 7미만의 임의의 실수값으로 채워진  4 x 2 x 2 배열을 생성하시오.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
배열의 모양: (4, 2, 2)
[[[6.3727774  5.33248683]
  [6.58527757 5.54165326]]

 [[5.22078554 5.65552663]
  [6.56711334 5.9770209 ]]

 [[6.9212381  6.58904435]
  [6.68180005 5.73738029]]

 [[5.30810951 5.83762379]
  [4.95383333 6.6055771 ]]]
```

### Problem: 정수형 랜덤 배열 생성하기
😄 10이상 20미만의 임의의 정수로 채워진 3 x 2 x 5 배열을 생성하시오.

---

<font color='blue'>`test case-1`</font> 

Output Sample
```
배열의 모양: (3, 2, 5)
[[[18 16 14 12 14]
  [18 14 12 16 10]]

 [[10 14 16 14 11]
  [16 10 18 13 14]]

 [[17 17 15 17 18]
  [12 16 11 18 17]]]
```

## [도전 실습 문제]

### Problem: 집합 가지고 놀기
😄 입력으로 세 줄에 걸쳐 각 집합(순서대로 A, B, C)에 해당하는 원소들이 들어옵니다. 각 줄은 공백으로 구분된 1에서 100 사이의 정수 1-30개로 이루어집니다. 

각 줄 안에서 원소가 겹칠 수 있는데, 이 때 그 줄에 해당하는 집합에서는 그 원소가 1개씩만 있다고 생각해야 합니다. 가령 첫 줄에 ‘3 4 5 4 3’이 들어오면 A={3, 4, 5}가 됩니다.

세 집합 A, B, C가 있을 때 A∩B∩C의 기수와 (A∪B∪C)-A의 기수를 구해 봅시다. 기수는 원소 개수를 의미합니다.

---

<font color='blue'>`test case-1`</font> 

Input Sample
```
2 4 5
1 2 2 1 10 4
3 3 3 4
```

Output Sample
```
A:
B:
C:
A∩B∩C의 기수: 1
(A∪B∪C)-A의 기수: 3
```

<font color='blue'>`test case-2`</font> 

Input Sample
```
20 25 29 21 16
1 4 5 6 9 25
4 7 7 9 12 21 18 15
```

Output Sample
```
A:
B:
C:
A∩B∩C의 기수: 0
(A∪B∪C)-A의 기수: 9
```

### Problem: 메뉴 추천
😄 공백으로 구분된 메뉴의 이름(key)과 공백으로 구분된 가격(value)에 대한 정보를 입력받아 딕셔너리 타입의 변수 menu에 저장하고, 변수 menu를 활용하여 가장 저렴한 메뉴와 가장 비싼 메뉴를 Output Samples와 같이 추천하는 프로그램을 작성하시오.
모든 메뉴의 이름과 가격은 다르며 모든 메뉴의 가격은 0이상 100000 이하입니다.

---

<font color='blue'>`test case-1`</font> 

Input Sample
```
ham bread chicken egg
1200 5000 17000 500
```

Output Sample
```
메뉴 이름: 
가격: 
Cheapest food: egg
Most expensive food: chicken
```

### Problem: The game of death (술게임)
😄 'The game of death' 게임에서 최종적으로 술을 마셔야하는 사람을 출력해봅시다.
게임이 시작할 때 각 사람이 다른 한 사람을 한 손으로 지목합니다. 각 사람과 지목하고 있는 사람의 정보가 딕셔너리 형태로 입력됩니다.
그리고 랜덤으로 시작하는 사람과 특정 숫자가 주어집니다. 그러면 시작하는 사람부터 시작하여 가리켜진 사람에게 넘어가면서 숫자를 하나씩 카운트하며, 카운트하고 있는 숫자가 특정 숫자가 될 때까지 이 과정을 반복합니다. 특정 숫자가 되었을 때 최종적으로 지목된 사람이 술을 마시게 됩니다.
각 사람이 지목하고 있는 사람 (dictionary), 시작하는 사람, 특정 숫자가 주어집니다.

---

<font color='blue'>`test case-1`</font> 

Input Sample
```
{'홍철': '하하', '하하' : '길', '명수': '재석', '재석': '길', '길': '재석'}
홍철
6
```

Output Sample
```
각 사람과 지목하고 있는 사람의 정보: 
시작하는 사람: 
특정 숫자: 
술 마실 사람: 길
```
<font color='blue'>`test case-2`</font> 

Input Sample
```
{'홍철': '신혜', '하하' : '길', '명수': '재석', '재석': '홍철', '길': '명수', '신혜': '길'}
홍철
5
```

Output Sample
```
각 사람과 지목하고 있는 사람의 정보: 
시작하는 사람: 
특정 숫자: 
술 마실 사람: 홍철
```

<div align="center"><img src="https://haesunbyun.github.io/common/images/death.png" style="width:500px;"></div>

### Problem: 성적총점과 각 과목 평균구하기
😄 Array를 이용하여 다음과 같이 실행되는 프로그램을 작성하시오.
학생 수가 먼저 입력되고 학생별 국,영,수 과목 성적이 콤마로 구분되어 차례대로 들어옵니다.

---

<font color='blue'>`test case-1`</font> 

Input Sample
```
3
50,60,80
80,70,90
70,80,80
```

Output Sample
```
학생 수: 
1번째 학생 국,영,수: 
2번째 학생 국,영,수:  
3번째 학생 국,영,수:  
학생들의 성적: 
[[50 60 80] 
 [80 70 90]
 [70 80 80]] 
각 학생의 총점: 
[190 240 230] 
각 과목의 평균: 
[66.67 70. 83.33]
```

:::{admonition} round()함수  
:class: tip

numpy에서의 round()함수는 np.round(값, 소수점 자리수)와 같이 사용한다.

또는 array명.round(소수점 자리수)와 같이 사용한다.

:::

## [완전 실습 문제]

### Problem: 주소 슬라이싱하기
😄 '시', '구', '동', '로' 등의 주소 데이터만 슬라이싱하여 출력하는 프로그램을 작성하시오. 주소는 '동'이나 '로'로 끝나며 '시'-'구'-'동' 또는 '시'-'구'-'로'의 순서가 항상 지켜진다고 가정한다.

<font color='blue'>`test case-1`</font> 
---
Input Sample
```
['02-334-0000', '서울시', '노원구', '가즈아로', '낙엽', '서울시', '관악구', '강감찬로', '콜라', '02-3334-1200', '서울시', '강남구', '섬그늘로', '서울시', '노원구', '경춘선숲길', '상계동', '02-1124-5670']
```
Output Sample
```
Input: 
Output: ['서울시 노원구 가즈아로', '서울시 관악구 강감찬로', '서울시 강남구 섬그늘로', '서울시 노원구 상계동']
```
<font color='blue'>`test case-2`</font> 
---
Input Sample
```
['010-342-1234','경기','가을단풍', '인천시','남구','벚꽃로', '벚꽃길', '이쁘다', '광주시','남구','무등산','수박','진월동', '부산광역시','서구','해운대로','부산행']
```
Output Sample
```
Input: 
Output: ['인천시 남구 벚꽃로', '광주시 남구 진월동', '부산광역시 서구 해운대로']

```

### Problem: 가중치적용하여 성적구하기
😄 배열변수 scores에는 앞에서부터 번호, 국어, 영어, 수학, 체육, 컴기의 시험점수가 들어있습니다.

전체 평균점수가 가장 높은 학생 번호를 구하시오.

전체 평균점수가 가장 낮은 학생 번호를 구하시오.

국어, 영어, 수학 점수의 평균이 가장 높은 학생 번호를 구하시오.

국어, 영어, 수학 점수에 2배 가중치를 준다면 5과목의 평균 점수가 가장 높은 학생의 번호를 구하시오.



```
scores=np.array([[23231., 70., 85., 95., 100., 100.],
          [23232., 100., 84., 90., 90., 95.],   
          [23233., 95., 95., 80., 75., 75.],          
          [23234., 65., 75., 70., 90., 100.],
          [23235., 90., 80., 85., 95., 95.],          
          [23236., 90., 90., 95., 75., 80.],          
          [23237., 60., 90., 80., 40., 45.],          
          [23238., 85., 90., 75., 60., 90.],              
          [23239., 90., 85., 85., 90., 85.]])
```

---


<font color='blue'>`test case-1`</font> 

Output Sample
```
전체 평균점수가 가장 높은 학생 번호:  23232
전체 평균점수가 가장 낮은 학생 번호:  23237
국,영,수 평균이 가장 높은 학생 번호:  23236
국,영,수 2배 가중치 평균이 가장 높은 학생 번호:  23232
```